image: erlang:21-slim

before_script:
  - apt-get update -y
  - apt-get -y install build-essential libssl-dev openssl

test:
  artifacts:
    when: always
    paths:
    - _build/test/logs
    - _build/test/cover

  script:
    - rm -rf _build/test
    - rebar3 as test ct

  cache:
    paths:
    - _build/default/lib/eleveldb
    - _build/test/lib/eleveldb
