kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: bondy
    tier: gateway
  name: bondy-claim
  namespace: magenta
  {{- if ne .name "packet" }}
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if eq .name "packet" }}
  selector:
    matchLabels:
      app: "bondy"
  {{- end }}
