# Servicio con load-balancer para los microservicios
kind: Service
apiVersion: v1
metadata:
  name: testbondy
  namespace: {{ .magenta.namespace }}
  labels:
    app: testbondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 80
      targetPort: 18080
    - name: admin
      port: 8081
      targetPort: 18081
    - name: wamp
      port: 8080
      targetPort: 18082
  type: ClusterIP
  selector:
    app: testbondy
