# Service externo, para admin y api
kind: Service
apiVersion: v1
metadata:
  name: bondy-export
  namespace: magenta
  labels:
    app: bondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 18080
      {{- if eq .name "packet" }}
      nodePort: 32500
      {{- end }}
    - name: admin
      port: 8081
      targetPort: 18081
      {{- if eq .name "packet" }}
      nodePort: 32501
      {{- end }}
  {{- if eq .name "packet" }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}
  selector:
    app: bondy
