# Servicio headless para tener un fqdn en bondy (Interno a bondy)
kind: Service
apiVersion: v1
metadata:
  name: bondy-fqdn
  namespace: {{ .bondy.namespace }}
  labels:
    app: bondy
    tier: gateway
spec:
  ports:
    - name: wamp
      port: 8080
      targetPort: 18082
  type: ClusterIP
  clusterIP: None
  selector:
    app: bondy
