# Service externo, para admin y api
kind: Service
apiVersion: v1
metadata:
  name: bondy-export
  namespace: {{ .magenta.namespace }}
  labels:
    app: bondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 18080
      {{- if eq .bondy.exportType "NodePort" }}
      nodePort: 32500
      {{- end }}
  type: {{ .bondy.exportType }}
  selector:
    app: bondy
