# Service externo, para admin y api
kind: Service
apiVersion: v1
metadata:
  name: bondy-export
  namespace: {{ .magenta.namespace }}
  labels:
    app: bondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 18080
      {{- if eq .bondy.exportType "NodePort" }}
      nodePort: {{ .magenta.nodePorts.bondyApi }}
      {{- end }}
    - name: admin
      port: 8081
      targetPort: 18081
      {{- if eq .bondy.exportType "NodePort" }}
      nodePort: {{ .magenta.nodePorts.bondyAdmin }}
      {{- end }}
  type: {{ .bondy.exportType }}
  selector:
    app: bondy
