{{- if eq .magenta.exportType "service" }}
# Service externo, para admin y api
kind: Service
apiVersion: v1
metadata:
  name: testbondy-export
  namespace: {{ .infra.namespace }}
  labels:
    app: testbondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 18080
      {{- if eq .testbondy.exportType "NodePort" }}
      nodePort: {{ .magenta.nodePorts.testbondyApi }}
      {{- end }}
    - name: admin
      port: 8081
      targetPort: 18081
      {{- if eq .testbondy.exportType "NodePort" }}
      nodePort: {{ .magenta.nodePorts.testbondyAdmin }}
      {{- end }}
  type: {{ .testbondy.exportType }}
  selector:
    app: testbondy
{{- end }}