kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: bondy
    tier: gateway
  name: bondy-claim
  namespace: magenta
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "default"
  selector:
    matchLabels:
      app: "bondy"
