swagger: '2.0'

# This is your document metadata
info:
  version: "0.1.0"
  title: Bondy

# Describe your paths here
paths:
  /   :
    get:
      description: |
        List the available resources.
      responses:
        200:
          description: Successful response
          schema:
            title: ArrayOfResources
            type: array
            items:
              title: Resource
              type: string
  /ping   :
    get:
      description: |
        Checks if the server is alive. This is useful for monitoring tools, load-balancers and automated scripts.
      responses:
        200:
          description: Successful response
  /stats  :
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Reports about the performance and configuration of the Bondy node to which it was requested. You must have the {bondy_stat,true} configuration setting in app.config for this endpoint to be active.
      parameters:
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        404:
          description: The statistics are not enabled.
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Stats
            type: object
            properties:
              cpu_nprocs:
                description: Foo
                type: integer
              cpu_avg1:
                type: integer
              cpu_avg5:
                type: integer
              cpu_avg15:
                type: integer
              mem_total:
                type: float
              mem_allocated:
                type: float
              nodename:
                type: string
              connected_nodes:
                type: array
              ws_active:
                description: Number of active WebSockets connections
                type: integer
              ws_connects:
                description: Total number of WebSockets connections made
                type: integer
              ws_connects_60s:
                description: Number of WebSockets connections made in the last minute
                type: integer
              tcp_active:
                description: Number of active TCP/IP connections
                type: integer
              tcp_connects:
                description: Total number of TCP/IP connections made
                type: integer
              tcp_connects_60s:
                description: Number of TCP/IP connections made in the last minute
                type: integer
              calls_60s:
                description: Number of RPC calls received by this node in the last minute
                type: integer
              calls:
                description: Total number of RPC calls received by this node
                type: integer
              registrations_active:
                description: Number of RPC registrations active in this node
                type: integer
              registrations_active_60s:
                description: Number of RPC registrations active in this node in the last minute
                type: integer
              subscriptions:
                description: Number of Pub-Sub subscriptions active in this node in the last minute
                type: integer
              subscriptions_active:
                description: Number of Pub-Sub subscriptions active in this node in the last minute
                type: integer
  /apis/{uri}   :
    get:
      description: |
        The API Collection Resource represents the APIs exposed by BONDY's API Gateway capability.
      responses:
        200:
          description: Successful response  
          schema:
            title: API
            type: object
            properties: 
              procedure:
                description: reverse uri identifying this API e.g. `com.mycompany.foo`
                type: string
              baseurl:
                description: The base URL that points to the API e.g. `https://www.mycompany.com/api`
                type: string
              url:
                description: The realtive url to resolve against the baseurl property to construct the invocation e.g. `/status`
                type: string
              method:
                description: The HTTP method to be used on the remote url (host+path)
                type: string
              created_at:
                description: The date in which this entry was created at
                type: integer
  /example  :
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Reports about the performance and configuration of the Bondy node to which it was requested. You must have the {bondy_stat,true} configuration setting in app.config for this endpoint to be active.
      parameters:
        -
          name: size
          in: query
          description: Size of array
          required: true
          type: number
          format: double
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean